language: ruby

rvm:
  ruby-2.4.1

before_script: 
  gem install awesome_bot

script: 
  wl=https://github.com/,http://git.io/
  
  awesome_bot README.md --allow-redirect --allow-dupe --white-list $wl

notifications:
  email: false
